# Page settings
baseurl = "https://cfp.atom.im"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

disableHugoGeneratorInject = true

[blackfriday]
fractions = false
hrefTargetBlank = true

# Meta
[params]
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu Wan"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected conferences in computer architecture & system fields."
notes = "**Note**: Deadlines are shown in timezone from conference website. Timelines and countdowns are shown in Asia/Hong_Kong timezone. Deadlines for conferences with * have not yet been announced."

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://ccf.atom.im). Report bug at [here](https://github.com/atom-im/cfp/issues)."

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im)."

# Timeline section
[params.timeline]
enable = true

# Highlight section
[params.highlight]
enable = true
title = "Featured CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Inactive CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
[params.past]
enable = true
title = "Past CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event Status"

# Important dates of conferences
# NOTE 1: enable (0: hide, 1: show, 2: highlight)
# NOTE 2: date format: 2006-01-02 15:04:05 -07:00
#         must two digits for each field
[[params.cfp.list]]
enable = 2
name = "ASPLOS Summer"
rank = "A"
site = "https://asplos-conference.org/"
open = "2023-02-28"
close = "2023-03-04 23:59:59 -04:00"
absddl = "2022-06-30 17:59:59 -04:00"
submddl = "2022-07-07 17:59:59 -04:00"
notidue = "2022-09-22"

[[params.cfp.list]]
enable = 1
name = "ASPLOS Fall"
rank = "A"
site = "https://asplos-conference.org/"
open = "2023-02-28"
close = "2023-03-04 23:59:59 -04:00"
absddl = "2022-10-13 17:59:59 -04:00"
submddl = "2022-10-20 17:59:59 -04:00"
notidue = "2023-01-19"

[[params.cfp.list]]
enable = 1
name = "FAST"
rank = "A"
site = "https://www.usenix.org/conference/fast23/call-for-papers"
open = "2023-02-20"
close = "2023-02-23 23:59:59"
absddl = "N/A"
submddl = "2022-09-22 23:59:59 -07:00"
notidue = "2022-12-09"

[[params.cfp.list]]
enable = 1
name = "HPCA"
rank = "A"
site = "https://www.hpca-conf.org/2023/"
open = "2023-02-25"
close = "2023-03-01 23:59:59 +09:00"
absddl = "2022-07-25 23:59:59 +00:00"
submddl = "2022-08-01 23:59:59 +00:00"
notidue = "2022-10-18"

[[params.cfp.list]]
enable = 1
name = "ISCA"
rank = "A"
site = "https://iscaconf.org/isca2022"
open = "2022-06-11"
close = "2022-06-15 23:59:59"
absddl = "2021-11-16 23:59:00 -12:00"
submddl = "2021-11-23 23:59:00 -12:00"
notidue = "2022-03-02"

[[params.cfp.list]]
enable = 1
name = "MICRO"
rank = "A"
site = "https://www.microarch.org/micro55"
open = "2022-10-16"
close = "2022-10-20 23:59:59"
absddl = "2022-04-14 23:59:59 -07:00"
submddl = "2022-04-21 23:59:59 -07:00"
notidue = "2022-07-18"

[[params.cfp.list]]
enable = 1
name = "SC"
rank = "A"
site = "https://sc22.supercomputing.org"
open = "2022-11-13"
close = "2022-11-18 23:59:59"
absddl = "2022-03-25 23:59:00 -12:00"
submddl = "2022-04-01 23:59:00 -12:00"
notidue = "2022-06-13"

[[params.cfp.list]]
enable = 1
name = "ATC"
rank = "A"
site = "https://www.usenix.org/conference/atc23"
open = "2023-07-10"
close = "2023-07-12 23:59:59"
absddl= "2023-01-05 23:59:59 +00:00"
submddl = "2023-01-12 23:59:59 +00:00"
notidue = "2023-04-28"

[[params.cfp.list]]
enable = 1
name = "PPoPP"
rank = "A"
site = "https://ppopp23.sigplan.org"
open = "2023-02-25"
close = "2023-03-01 23:59:59 +09:00"
absddl = "N/A"
submddl = "2022-08-17"
notidue = "2023-01-06"

[[params.cfp.list]]
enable = 1
name = "SPAA"
rank = "B"
site = "http://spaa.acm.org/"
open = "2023-06-16"
close = "2023-06-19 23:59:59"
absddl = "2023-01-12 23:59:59 -12:00"
submddl = "2023-01-16 23:59:59 -12:00"
notidue = "2023-03-22"

[[params.cfp.list]]
enable = 1
name = "PODC"
rank = "B"
site = "https://www.podc.org/"
open = "2023-06-19"
close = "2023-06-23 23:59:59"
absddl = "2023-01-06 23:59:59 -12:00"
submddl = "2023-01-10 23:59:59 -12:00"
notidue = "2023-03-30"

[[params.cfp.list]]
enable = 1
name = "DAC"
rank = "A"
site = "https://dac.com"
open = "2023-07-09"
close = "2023-07-13 23:59:59"
absddl = "2022-11-14 17:00:00 -08:00"
submddl = "2022-11-21 17:00:00 -08:00"
notidue = "2023-02-23"

[[params.cfp.list]]
enable = 1
name = "DATE"
rank = "B"
site = "https://www.date-conference.com/"
open = "2023-04-17"
close = "2023-04-19 23:59:59"
absddl = "2022-09-18 23:59:59 -12:00"
submddl = "2022-09-25 23:59:59 -12:00"
notidue = "2022-11-11"

[[params.cfp.list]]
enable = 1
name = "EuroSys (Spring)"
rank = "B"
site = "https://2023.eurosys.org/"
open = "2023-05-09"
close = "2023-05-12 23:59:59"
absddl = "2022-05-11 23:59:59 -12:00"
submddl = "2022-05-18 23:59:59 -12:00"
notidue = "2022-08-10 23:59:59 -12:00"

[[params.cfp.list]]
enable = 1
name = "EuroSys (Fall)"
rank = "B"
site = "https://2023.eurosys.org/"
open = "2023-05-09"
close = "2023-05-12 23:59:59"
absddl = "2022-10-12"
submddl = "2022-10-19"
notidue = "2023-01-18"

[[params.cfp.list]]
enable = 1
name = "HPDC*"
rank = "B"
site = "http://www.hpdc.org/2023/"
open = "2023-06-16"
close = "2023-06-23 23:59:59"
absddl = "2023-01-20 23:59:59 -12:00"
submddl = "2023-01-27 23:59:59 -12:00"
notidue = "2023-03-31"

[[params.cfp.list]]
enable = 1
name = "ICCD"
rank = "B"
site = "http://www.iccd-conf.com"
open = "2022-10-23"
close = "2022-10-26 23:59:59"
absddl = "2022-06-04 23:59:59 -12:00"
submddl = "2022-06-11 23:59:59 -12:00"
notidue = "2022-08-21"

[[params.cfp.list]]
enable = 0
name = "ICCAD"
rank = "B"
site = "http://www.iccad-conf.com"
open = "2019-07-02"
close = "2019-07-03 23:59:59"
absddl = "N/A"
submddl = "2020-01-31"
notidue = "2020-03-31"

[[params.cfp.list]]
enable = 1
name = "HiPEAC"
rank = "B"
site = "https://www.hipeac.net/2023/toulouse/#/"
open = "2023-01-16"
close = "2023-01-18 23:59:59"
absddl = "N/A"
submddl = "2022-06-01"
notidue = "2022-11-15"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS-2"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2023"
open = "2023-06-19"
close = "2023-06-23 23:59:59"
absddl = "2022-10-12"
submddl = "2022-10-19"
notidue = "2022-12-20"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS-3"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2023"
open = "2023-06-19"
close = "2023-06-23 23:59:59"
absddl = "2023-01-25"
submddl = "2023-02-01"
notidue = "2023-03-28"

[[params.cfp.list]]
enable = 1
name = "ICPP"
rank = "B"
site = "http://www.icpp-conf.org"
open = "2022-08-29"
close = "2022-09-01 23:59:59"
absddl = "2022-04-08 23:59:59 -12:00"
submddl = "2022-04-14 23:59:59 -12:00"
notidue = "2022-06-14"

[[params.cfp.list]]
enable = 1
name = "ICS"
rank = "B"
site = "https://ics2022.github.io/"
open = "2022-06-27"
close = "2022-06-30 23:59:59"
absddl = "2022-01-28"
submddl = "2022-02-04"
notidue = "2022-04-14"

[[params.cfp.list]]
enable = 1
name = "IPDPS"
rank = "B"
site = "http://www.ipdps.org/"
open = "2023-05-15"
close = "2023-05-19 23:59:59"
absddl = "2022-09-29 23:59:59 -12:00"
submddl = "2022-10-06 23:59:59 -12:00"
notidue = "2023-01-31"

[[params.cfp.list]]
enable = 1
name = "MSST"
rank = "B"
site = "http://storageconference.us/"
open = "2020-10-26"
close = "2020-10-30 23:59:59"
absddl = "N/A"
submddl = "2020-01-07"
notidue = "2020-02-15"

[[params.cfp.list]]
enable = 1
name = "PACT"
rank = "B"
site = "https://pact22.cs.illinois.edu/"
open = "2022-10-10"
close = "2022-10-12 23:59:59"
absddl = "N/A"
submddl = "2022-04-18"
notidue = "2022-04-25"

[[params.cfp.list]]
enable = 1
name = "OOPSLA"
rank = "A"
site = "https://2022.splashcon.org/"
open = "2022-11-14"
close = "2022-11-19 23:59:59"
absddl = "N/A"
submddl = "2022-04-15"
notidue = "2022-06-30"

[[params.cfp.list]]
enable = 1
name = "ICSE"
rank = "A"
site = "https://conf.researchr.org/home/icse-2023"
open = "2023-05-14"
close = "2023-05-20 23:59:59"
absddl = "N/A"
submddl = "2022-09-01 23:59:59 -12:00"
notidue = "2022-12-09"

[[params.cfp.list]]
enable = 1
name = "OSDI"
rank = "A"
site = "https://www.usenix.org/conference/osdi23/"
open = "2023-07-10"
close = "2023-07-12 23:59:59 -07:00"
absddl = "2022-12-06 22:59:00 +00:00"
submddl = "2022-12-13 22:59:00 +00:00"
notidue = "2022-03-23"

[[params.cfp.list]]
enable = 1
name = "PLDI"
rank = "A"
site = "http://pldi23.sigplan.org"
open = "2023-06-19"
close = "2023-06-23 23:59:59"
absddl = "N/A"
submddl = "2022-11-10"
notidue = "2023-02-23"

[[params.cfp.list]]
enable = 1
name = "POPL"
rank = "A"
site = "https://popl23.sigplan.org/"
open = "2023-01-15"
close = "2023-01-21 23:59:59"
absddl = "N/A"
submddl = "2022-10-26 23:59:59 -12:00"
notidue = "2022-11-07"

[[params.cfp.list]]
enable = 1
name = "SOSP*"
rank = "A"
site = "https://sosp2023.mpi-sws.org/"
open = "2023-10-23"
close = "2023-10-26 23:59:59"
absddl = "2023-04-30 02:59:59 -07:00"
submddl = "2023-05-07 02:59:59 -07:00"
notidue = "2023-08-09"

[[params.cfp.list]]
enable = 0
name = "HotOS"
rank = "B"
site = "https://www.sigops.org/2018/hotos2019/"
open = "2019-05-12"
close = "2019-05-15 23:59:59"
absddl = "N/A"
submddl = "2019-01-17"
notidue = "2019-03-11"

[[params.cfp.list]]
enable = 1
name = "SIGMOD-3"
rank = "A"
site = "https://2023.sigmod.org/"
open = "2023-06-18"
close = "2023-06-23 23:59:59"
absddl = "N/A"
submddl = "2022-10-15"
notidue = "2023-02-23"

[[params.cfp.list]]
enable = 1
name = "VLDB*"
rank = "A"
site = "http://vldb.org/2023/"
open = "2023-08-28"
close = "2023-09-01 23:59:59"
absddl = "2023-02-20"
submddl = "2023-03-01"
notidue = "2023-04-15"

[[params.cfp.list]]
enable = 1
name = "ICDE"
rank = "A"
site = "https://icde2023.ics.uci.edu/"
open = "2023-04-03"
close = "2023-04-07 23:59:59"
absddl = "N/A"
submddl = "2022-10-08 23:59:59 -08:00"
notidue = "2022-11-08"

[[params.cfp.list]]
enable = 0
name = "CIDR"
rank = "A"
site = "http://cidrdb.org/cidr2020/"
open = "2020-01-12"
close = "2020-01-15 23:59:59"
absddl = "N/A"
submddl = "2019-08-23 23:59:59 -07:00"
notidue = "2019-10-14"

[[params.cfp.list]]
enable = 0
name = "ESWEEK"
rank = "B"
site = "http://www.esweek.org"
open = "2022-10-07"
close = "2022-10-14 23:59:59"
absddl = "2022-03-31 23:59:59 -12:00"
submddl = "2022-04-07 23:59:59 -12:00"
notidue = "2022-07-05"


[[params.cfp.list]]
enable = 1
name = "EMSOFT"
rank = "B"
site = "http://www.esweek.org"
open = "2022-10-07"
close = "2022-10-14 23:59:59"
absddl = "2022-03-31 23:59:59 -12:00"
submddl = "2022-04-07 23:59:59 -12:00"
notidue = "2022-07-05"

[[params.cfp.list]]
enable = 1
name = "CODES+ISSS"
rank = "B"
site = "http://www.esweek.org"
open = "2022-10-07"
close = "2022-10-14 23:59:59"
absddl = "2022-03-31 23:59:59 -12:00"
submddl = "2022-04-07 23:59:59 -12:00"
notidue = "2022-07-05"

[[params.cfp.list]]
enable = 1
name = "NVMSA"
rank = ""
site = "https://nvmsa2022.github.io/index"
open = "2022-08-23"
close = "2022-08-25 23:59:59"
absddl = "N/A"
submddl = "2022-04-15 23:59:59 -12:00"
notidue = "2022-05-31"

[[params.cfp.list]]
enable = 1
name = "HotStorage"
rank = ""
site = "https://www.hotstorage.org/2022/"
open = "2022-06-27"
close = "2022-06-28 23:59:59"
absddl = "N/A"
submddl = "2022-03-29"
notidue = "2022-06-06"

[[params.cfp.list]]
enable = 1
name = "SysML"
rank = ""
site = "https://mlsys.org/"
open = "2023-06-04"
close = "2023-06-08 23:59:59"
absddl = "N/A"
submddl = "2022-10-28 19:59:59"
notidue = "2023-02-17"

[[params.cfp.list]]
enable = 1
name = "FPGA"
rank = "B"
site = "https://isfpga.org/"
open = "2023-02-12"
close = "2023-02-14 23:59:59"
absddl = "2022-09-16"
submddl = "2022-09-23"
notidue = "2022-11-30"

[[params.cfp.list]]
enable = 1
name = "FPL"
rank = "C"
site = "https://www.fpl.org/"
open = "2022-08-29"
close = "2022-09-02 23:59:59"
absddl = "2022-03-07"
submddl = "2022-03-14"
notidue = "2022-05-09"

[[params.cfp.list]]
enable = 1
name = "FPT"
rank = "C"
site = "http://www.icfpt.org/"
open = "2022-12-05"
close = "2022-12-09 23:59:59"
absddl = "2022-07-08"
submddl = "2022-07-15"
notidue = "2022-09-30"

[[params.cfp.list]]
enable = 1
name = "FCCM*"
rank = "C"
site = "https://www.fccm.org/"
open = "2023-05-15"
close = "2023-05-18 23:59:59"
absddl = "2023-01-09"
submddl = "2023-01-16"
notidue = "2023-03-21"

[[params.cfp.list]]
enable = 1
name = "APSys"
rank = ""
site = "https://ap-sys.org/"
open = "2022-08-23"
close = "2022-08-24 23:59:59"
absddl = "2022-04-29 23:59:00 -04:00"
submddl = "2022-05-06 23:59:00 -04:00"
notidue = "2022-06-17"

[[params.cfp.list]]
enable = 1
name = "RTSS"
rank = "A"
site = "http://2022.rtss.org/"
open = "2022-12-05"
close = "2022-12-08 23:59:59"
absddl = "N/A"
submddl = "2022-05-26 23:59:00 -12:00"
notidue = "2022-08-05"

[[params.cfp.list]]
enable = 1
name = "RTAS"
rank = "B"
site = "http://2023.rtas.org/"
open = "2023-05-09"
close = "2023-05-12 23:59:59"
absddl = "N/A"
submddl = "2022-10-31 23:59:00 -12:00"
notidue = "2023-01-20"

[[params.cfp.list]]
enable = 1
name = "CGO"
rank = "B"
site = "https://conf.researchr.org/home/cgo-2023"
open = "2023-02-25"
close = "2023-03-01 23:59:59"
absddl = "N/A"
submddl = "2022-09-02 23:59:00 -12:00"
notidue = "2022-11-07"
