# Page settings
baseurl = "https://cfp.atom.im"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

[blackfriday]
fractions = false
hrefTargetBlank = true

# Meta
[params]
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu Wan"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected conferences in computer architecture & system fields."
notes = "**Note**: Deadlines are shown in timezone from conference website. Timelines and countdowns are shown in Asia/Hong_Kong time."

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://ccf.atom.im). Report bug at [here](https://github.com/atom-im/cfp/issues)."

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im)."

# Timeline section
[params.timeline]
enable = true

# Highlight section
[params.highlight]
enable = true
title = "Featured Call"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming Calls"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Inactive Calls"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
[params.past]
enable = true
title = "Past Calls"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event Status"

[[params.cfp.list]]
enable = 1
name = "ASPLOS"
rank = "A"
site = "https://asplos-conference.org/"
open = "2020-03-16"
close = "2020-03-20 23:59:59 -07:00"
absddl = "2019-08-09 16:59:59 -07:00"
submddl = "2019-08-16 16:59:59 -07:00"
notidue = "2019-11-20"

[[params.cfp.list]]
enable = 1
name = "FAST"
rank = "A"
site = "https://www.usenix.org/conference/fast21/call-for-papers"
open = "2021-02-22"
close = "2021-02-25 23:59:59"
absddl = "N/A"
submddl = "2020-09-24 23:59:59 -07:00"
notidue = "2020-11-11"

[[params.cfp.list]]
enable = 2
name = "HPCA"
rank = "A"
site = "https://www.hpca-conf.org/2021/"
open = "2021-02-27"
close = "2021-03-03 23:59:59"
absddl = "2020-07-24 23:59:59 +09:00"
submddl = "2020-07-31 23:59:59 +09:00"
notidue = "2020-10-30"

[[params.cfp.list]]
enable = 1
name = "ISCA"
rank = "A"
site = "http://iscaconf.org/isca2020"
open = "2020-05-30"
close = "2020-06-03 23:59:59"
absddl = "2019-11-19"
submddl = "2019-11-26"
notidue = "2020-03-04"

[[params.cfp.list]]
enable = 1
name = "MICRO"
rank = "A"
site = "https://www.microarch.org/micro53"
open = "2020-10-17"
close = "2020-10-21 23:59:59"
absddl = "2020-04-10 23:59:59 -07:00"
submddl = "2020-04-17 23:59:59 -07:00"
notidue = "2020-07-07"

[[params.cfp.list]]
enable = 1
name = "SC"
rank = "A"
site = "https://sc20.supercomputing.org"
open = "2020-11-15"
close = "2020-11-20 23:59:59"
absddl = "2020-03-31"
submddl = "2020-04-08"
notidue = "2020-06-15"

[[params.cfp.list]]
enable = 1
name = "ATC"
rank = "A"
site = "https://www.usenix.org/conference/atc20/call-for-papers"
open = "2020-07-15"
close = "2020-07-17 23:59:59"
absddl = "N/A"
submddl = "2020-01-15 23:59:59 -05:00"
notidue = "2020-04-24"

[[params.cfp.list]]
enable = 1
name = "PPoPP"
rank = "A"
site = "https://ppopp20.sigplan.org"
open = "2020-02-22"
close = "2020-02-26 23:59:59"
absddl = "2019-07-31"
submddl = "2019-08-06"
notidue = "2019-11-19"

[[params.cfp.list]]
enable = 1
name = "SPAA"
rank = "B"
site = "http://spaa.acm.org/"
open = "2020-07-15"
close = "2020-07-17 23:59:59"
absddl = "2020-02-08"
submddl = "2020-02-15"
notidue = "2020-04-15"

[[params.cfp.list]]
enable = 1
name = "PODC"
rank = "B"
site = "https://www.podc.org/"
open = "2020-08-03"
close = "2020-08-07 23:59:59"
absddl = "N/A"
submddl = "2020-02-17"
notidue = "2020-05-04"

[[params.cfp.list]]
enable = 1
name = "DAC"
rank = "A"
site = "https://dac.com"
open = "2020-06-19"
close = "2020-06-23 23:59:59"
absddl = "2019-11-21"
submddl = "2019-11-27"
notidue = "2020-02-28"

[[params.cfp.list]]
enable = 1
name = "DATE"
rank = "B"
site = "https://www.date-conference.com/"
open = "2021-02-01"
close = "2021-02-05 23:59:59"
absddl = "2020-09-14 23:59:59 +02:00"
submddl = "2020-09-21 23:59:59 +02:00"
notidue = "2020-11-07"

[[params.cfp.list]]
enable = 1
name = "EuroSys"
rank = "B"
site = "https://2021.eurosys.org/"
open = "2021-04-26"
close = "2021-04-29 23:59:59"
absddl = "N/A"
submddl = "TBA"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "HPDC"
rank = "B"
site = "http://www.hpdc.org/2020/"
open = "2020-06-23"
close = "2020-06-26 23:59:59"
absddl = "2020-01-16"
submddl = "2020-01-23"
notidue = "2020-03-27"

[[params.cfp.list]]
enable = 1
name = "ICCD"
rank = "B"
site = "http://www.iccd-conf.com"
open = "2020-10-18"
close = "2020-10-21 23:59:59"
absddl = "2020-06-12 23:59:59 -12:00"
submddl = "2020-06-12 23:59:59 -12:00"
notidue = "2020-08-17"

[[params.cfp.list]]
enable = 0
name = "ICCAD"
rank = "B"
site = "http://www.iccad-conf.com"
open = "2019-07-02"
close = "2019-07-03 23:59:59"
absddl = "N/A"
submddl = "2020-01-31"
notidue = "2020-03-31"

[[params.cfp.list]]
enable = 1
name = "HiPEAC"
rank = "B"
site = "http://hipeac.net/conference"
open = "2021-01-18"
close = "2021-01-20 23:59:59"
absddl = "N/A"
submddl = "2020-11-15"
notidue = "2020-11-15"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2020"
open = "2020-06-08"
close = "2020-06-12 23:59:59"
absddl = "2020-01-27"
submddl = "2020-02-03"
notidue = "2020-03-31"

[[params.cfp.list]]
enable = 1
name = "ICPP"
rank = "B"
site = "http://www.icpp-conf.org"
open = "2020-08-17"
close = "2020-08-20 23:59:59 +09:00"
absddl = "2020-03-02"
submddl = "2020-03-09"
notidue = "2020-05-19"

[[params.cfp.list]]
enable = 1
name = "ICS"
rank = "B"
site = "https://ics2020.bsc.es/"
open = "2020-06-29"
close = "2020-07-02 23:59:59"
absddl = "2020-01-24"
submddl = "2020-01-31"
notidue = "2020-04-15"

[[params.cfp.list]]
enable = 1
name = "IPDPS"
rank = "B"
site = "http://www.ipdps.org/"
open = "2020-05-18"
close = "2020-05-22 23:59:59"
absddl = "2019-10-07 23:59:59 -12:00"
submddl = "2019-10-14 23:59:59 -12:00"
notidue = "2019-12-09"

[[params.cfp.list]]
enable = 1
name = "MSST"
rank = "B"
site = "http://storageconference.us/"
open = "2020-10-26"
close = "2020-10-30 23:59:59"
absddl = "N/A"
submddl = "2020-01-07"
notidue = "2020-02-15"

[[params.cfp.list]]
enable = 1
name = "PACT"
rank = "B"
site = "https://pact20.cc.gatech.edu/"
open = "2020-10-03"
close = "2020-10-07 23:59:59"
absddl = "2020-04-24"
submddl = "2020-04-24"
notidue = "2020-07-15"

[[params.cfp.list]]
enable = 1
name = "OOPSLA"
rank = "A"
site = "https://2020.splashcon.org/"
open = "2020-11-15"
close = "2020-11-20 23:59:59"
absddl = "N/A"
submddl = "2020-04-15"
notidue = "2020-07-01"

[[params.cfp.list]]
enable = 1
name = "ICSE"
rank = "A"
site = "https://conf.researchr.org/home/icse-2021"
open = "2021-05-23"
close = "2021-05-29 23:59:59"
absddl = "N/A"
submddl = "2020-08-28 23:59:59 -12:00"
notidue = "2020-12-17"

[[params.cfp.list]]
enable = 1
name = "OSDI"
rank = "A"
site = "https://www.usenix.org/conference/osdi20/"
open = "2020-11-04"
close = "2020-11-06 23:59:59 -07:00"
absddl = "2020-05-05 15:00:00 -07:00"
submddl = "2020-05-12 15:00:00 -07:00"
notidue = "2020-08-04"

[[params.cfp.list]]
enable = 1
name = "PLDI"
rank = "A"
site = "http://pldi20.sigplan.org"
open = "2020-06-15"
close = "2020-06-20 23:59:59"
absddl = "N/A"
submddl = "2019-11-22"
notidue = "2020-02-21"

[[params.cfp.list]]
enable = 1
name = "POPL"
rank = "A"
site = "https://popl21.sigplan.org/"
open = "2021-01-17"
close = "2021-01-22 23:59:59"
absddl = "N/A"
submddl = "2020-07-09 23:59:59 -12:00"
notidue = "2021-01-17"

[[params.cfp.list]]
enable = 1
name = "SOSP"
rank = "A"
site = "https://www.sigops.org/sosp/sosp19"
open = "2019-10-27"
close = "2019-10-30 23:59:59"
absddl = "2019-04-17"
submddl = "2019-04-24"
notidue = "2019-07-22"

[[params.cfp.list]]
enable = 1
name = "HotOS"
rank = "B"
site = "https://www.sigops.org/2018/hotos2019/"
open = "2019-05-12"
close = "2019-05-15 23:59:59"
absddl = "N/A"
submddl = "2019-01-17"
notidue = "2019-03-11"

[[params.cfp.list]]
enable = 1
name = "SIGMOD-2"
rank = "A"
site = "https://sigmod2020.org/"
open = "2020-06-14"
close = "2020-06-20 23:59:59"
absddl = "2019-10-15"
submddl = "2019-10-22"
notidue = "2020-01-17"

[[params.cfp.list]]
enable = 1
name = "VLDB"
rank = "A"
site = "https://vldb2020.org/"
open = "2020-08-31"
close = "2020-09-04 23:59:59"
absddl = "2020-02-20"
submddl = "2020-03-01"
notidue = "2020-04-15"

[[params.cfp.list]]
enable = 1
name = "ICDE-1"
rank = "A"
site = "https://www.utdallas.edu/icde/"
open = "2020-04-20"
close = "2020-04-24 23:59:59"
absddl = "2019-06-08"
submddl = "2019-06-15"
notidue = "2019-08-10"

[[params.cfp.list]]
enable = 1
name = "ICDE-2"
rank = "A"
site = "https://www.utdallas.edu/icde/"
open = "2020-04-20"
close = "2020-04-24 23:59:59"
absddl = "2019-10-08 23:59:59 -07:00"
submddl = "2019-10-15 23:59:59 -07:00"
notidue = "2019-12-14"

[[params.cfp.list]]
enable = 0
name = "CIDR"
rank = "A"
site = "http://cidrdb.org/cidr2020/"
open = "2020-01-12"
close = "2020-01-15 23:59:59"
absddl = "N/A"
submddl = "2019-08-23 23:59:59 -07:00"
notidue = "2019-10-14"

[[params.cfp.list]]
enable = 1
name = "EMSOFT"
rank = "B"
site = "http://www.esweek.org"
open = "2020-10-11"
close = "2020-10-16 23:59:59"
absddl = "2020-04-03"
submddl = "2020-04-10"
notidue = "2020-07-06"

[[params.cfp.list]]
enable = 1
name = "CODES+ISSS"
rank = "B"
site = "http://www.esweek.org"
open = "2020-10-11"
close = "2020-10-16 23:59:59"
absddl = "2020-04-03"
submddl = "2020-04-10"
notidue = "2020-07-06"

[[params.cfp.list]]
enable = 1
name = "NVMSA"
rank = "-"
site = "https://nvmsa2020.github.io/index"
open = "2020-08-19"
close = "2020-08-21 23:59:59"
absddl = "2020-05-01 23:59:59 +09:00"
submddl = "2020-05-08 23:59:59 +09:00"
notidue = "2020-05-29"

[[params.cfp.list]]
enable = 1
name = "HotStorage"
rank = "-"
site = "https://www.usenix.org/conference/hotstorage20"
open = "2020-07-13"
close = "2020-07-14 23:59:59"
absddl = "N/A"
submddl = "2020-03-26"
notidue = "2020-04-30"

[[params.cfp.list]]
enable = 1
name = "SysML"
rank = "-"
site = "https://systemsandml.org"
open = "2020-03-02"
close = "2020-03-04 23:59:59"
absddl = "N/A"
submddl = "2019-09-09 16:59:59 -12:00"
notidue = "2020-01-03"
