# Page settings
baseurl = "https://cfp.atom.im"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

disableHugoGeneratorInject = true

[blackfriday]
fractions = false
hrefTargetBlank = true

# Meta
[params]
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu Wan"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected conferences in computer architecture & system fields."
notes = "**Note**: Deadlines are shown in timezone from conference website. Timelines and countdowns are shown in Asia/Hong_Kong timezone. Deadlines for conferences with * have not yet been announced."

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://ccf.atom.im). Report bug at [here](https://github.com/atom-im/cfp/issues)."

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im)."

# Timeline section
[params.timeline]
enable = true

# Highlight section
[params.highlight]
enable = true
title = "Featured CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Inactive CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
[params.past]
enable = true
title = "Past CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event Status"

# Important dates of conferences
# NOTE 1: enable (0: hide, 1: show, 2: highlight)
# NOTE 2: date format: 2006-01-02 15:04:05 -07:00
#         must two digits for each field
[[params.cfp.list]]
enable = 1
name = "ASPLOS"
rank = "A"
site = "https://asplos-conference.org/"
open = "2022-02-28"
close = "2022-03-04 23:59:59 -07:00"
absddl = "2021-08-06 14:59:59 -07:00"
submddl = "2021-08-13 14:59:59 -07:00"
notidue = "2021-11-15"

[[params.cfp.list]]
enable = 1
name = "FAST"
rank = "A"
site = "https://www.usenix.org/conference/fast22/call-for-papers"
open = "2022-02-21"
close = "2022-02-24 23:59:59"
absddl = "N/A"
submddl = "2021-09-23 23:59:59 -07:00"
notidue = "2021-12-10"

[[params.cfp.list]]
enable = 1
name = "HPCA"
rank = "A"
site = "https://www.hpca-conf.org/2022/"
open = "2022-04-02"
close = "2022-04-06 23:59:59 +09:00"
absddl = "2021-07-23 23:59:59 +00:00"
submddl = "2021-07-30 23:59:59 +00:00"
notidue = "2021-10-27"

[[params.cfp.list]]
enable = 1
name = "ISCA"
rank = "A"
site = "https://iscaconf.org/isca2022"
open = "2022-06-11"
close = "2022-06-15 23:59:59"
absddl = "2021-11-16 23:59:00 -12:00"
submddl = "2021-11-23 23:59:00 -12:00"
notidue = "2022-03-02"

[[params.cfp.list]]
enable = 1
name = "MICRO"
rank = "A"
site = "https://www.microarch.org/micro54"
open = "2021-10-16"
close = "2021-10-20 23:59:59"
absddl = "2021-04-09 23:59:59 -07:00"
submddl = "2021-04-16 23:59:59 -07:00"
notidue = "2021-07-14"

[[params.cfp.list]]
enable = 1
name = "SC"
rank = "A"
site = "https://sc22.supercomputing.org"
open = "2022-11-13"
close = "2022-11-18 23:59:59"
absddl = "2022-03-25 23:59:00 -12:00"
submddl = "2022-04-01 23:59:00 -12:00"
notidue = "2022-06-13"

[[params.cfp.list]]
enable = 2
name = "ATC"
rank = "A"
site = "https://www.usenix.org/conference/atc22"
open = "2022-07-11"
close = "2022-07-13 23:59:59"
absddl= "2022-01-06 23:59:59 +00:00"
submddl = "2022-01-13 23:59:59 +00:00"
notidue = "2022-04-29"

[[params.cfp.list]]
enable = 1
name = "PPoPP"
rank = "A"
site = "https://ppopp22.sigplan.org"
open = "2022-02-12"
close = "2022-02-16 23:59:59"
absddl = "2021-08-09"
submddl = "2021-08-13"
notidue = "2021-11-16"

[[params.cfp.list]]
enable = 1
name = "SPAA"
rank = "B"
site = "http://spaa.acm.org/"
open = "2022-07-11"
close = "2022-07-14 23:59:59"
absddl = "2022-02-04 23:59:59 -12:00"
submddl = "2022-02-11 23:59:59 -12:00"
notidue = "2022-04-29"

[[params.cfp.list]]
enable = 1
name = "PODC"
rank = "B"
site = "https://www.podc.org/"
open = "2022-07-25"
close = "2022-07-29 23:59:59"
absddl = "2022-02-10 23:59:59 -12:00"
submddl = "2022-02-13 23:59:59 -12:00"
notidue = "2022-05-03"

[[params.cfp.list]]
enable = 1
name = "DAC"
rank = "A"
site = "https://dac.com"
open = "2022-07-10"
close = "2022-07-14 23:59:59"
absddl = "2021-11-15 17:00:00 -08:00"
submddl = "2021-11-22 17:00:00 -08:00"
notidue = "2022-02-21"

[[params.cfp.list]]
enable = 1
name = "DATE"
rank = "B"
site = "https://www.date-conference.com/"
open = "2022-03-14"
close = "2022-03-23 23:59:59"
absddl = "2021-09-12 23:59:59 -12:00"
submddl = "2021-09-19 23:59:59 -12:00"
notidue = "2021-11-11"

[[params.cfp.list]]
enable = 1
name = "EuroSys"
rank = "B"
site = "https://2022.eurosys.org/"
open = "2022-04-05"
close = "2022-04-08 23:59:59"
absddl = "2021-10-01"
submddl = "2021-10-09"
notidue = "2022-01-20"

[[params.cfp.list]]
enable = 1
name = "HPDC"
rank = "B"
site = "http://www.hpdc.org/2022/"
open = "2022-06-27"
close = "2022-07-01 23:59:59"
absddl = "2022-01-20 23:59:59 -12:00"
submddl = "2022-01-27 23:59:59 -12:00"
notidue = "2022-03-31"

[[params.cfp.list]]
enable = 1
name = "ICCD"
rank = "B"
site = "http://www.iccd-conf.com"
open = "2021-10-24"
close = "2021-10-27 23:59:59"
absddl = "2021-05-28 23:59:59 -12:00"
submddl = "2021-06-04 23:59:59 -12:00"
notidue = "2021-08-20"

[[params.cfp.list]]
enable = 0
name = "ICCAD"
rank = "B"
site = "http://www.iccad-conf.com"
open = "2019-07-02"
close = "2019-07-03 23:59:59"
absddl = "N/A"
submddl = "2020-01-31"
notidue = "2020-03-31"

[[params.cfp.list]]
enable = 1
name = "HiPEAC"
rank = "B"
site = "https://www.hipeac.net/2022/budapest/#/"
open = "2022-01-17"
close = "2022-01-29 23:59:59"
absddl = "N/A"
submddl = "2021-11-15"
notidue = "2021-11-15"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2022"
open = "2022-06-06"
close = "2022-06-10 23:59:59"
absddl = "2022-01-26"
submddl = "2022-02-02"
notidue = "2022-03-28"

[[params.cfp.list]]
enable = 1
name = "ICPP"
rank = "B"
site = "http://www.icpp-conf.org"
open = "2022-08-29"
close = "2022-09-01 23:59:59"
absddl = "2022-04-08 23:59:59 -12:00"
submddl = "2022-04-14 23:59:59 -12:00"
notidue = "2022-06-14"

[[params.cfp.list]]
enable = 1
name = "ICS"
rank = "B"
site = "https://ics21.github.io/"
open = "2021-06-14"
close = "2021-06-17 23:59:59"
absddl = "2021-01-28"
submddl = "2021-02-04"
notidue = "2021-03-31"

[[params.cfp.list]]
enable = 1
name = "IPDPS"
rank = "B"
site = "http://www.ipdps.org/"
open = "2022-05-30"
close = "2022-06-03 23:59:59"
absddl = "2021-10-01 23:59:59 -12:00"
submddl = "2021-10-08 23:59:59 -12:00"
notidue = "2022-01-15"

[[params.cfp.list]]
enable = 1
name = "MSST"
rank = "B"
site = "http://storageconference.us/"
open = "2020-10-26"
close = "2020-10-30 23:59:59"
absddl = "N/A"
submddl = "2020-01-07"
notidue = "2020-02-15"

[[params.cfp.list]]
enable = 1
name = "PACT"
rank = "B"
site = "http://ssd.sscc.ru/conference/pact2021/"
open = "2021-10-03"
close = "2021-10-07 23:59:59"
absddl = "N/A"
submddl = "2021-03-31"
notidue = "2021-04-15"

[[params.cfp.list]]
enable = 1
name = "OOPSLA"
rank = "A"
site = "https://2022.splashcon.org/"
open = "2022-11-14"
close = "2022-11-19 23:59:59"
absddl = "N/A"
submddl = "2022-04-15"
notidue = "2022-06-30"

[[params.cfp.list]]
enable = 1
name = "ICSE"
rank = "A"
site = "https://conf.researchr.org/home/icse-2022"
open = "2022-05-21"
close = "2022-05-29 23:59:59"
absddl = "2021-08-27"
submddl = "2021-09-03 23:59:59"
notidue = "2021-12-03"

[[params.cfp.list]]
enable = 1
name = "OSDI"
rank = "A"
site = "https://www.usenix.org/conference/osdi22/"
open = "2022-07-11"
close = "2022-07-13 23:59:59 -07:00"
absddl = "2021-12-07 15:00:00 -07:00"
submddl = "2021-12-14 15:00:00 -07:00"
notidue = "2022-03-16"

[[params.cfp.list]]
enable = 1
name = "PLDI"
rank = "A"
site = "http://pldi22.sigplan.org"
open = "2022-06-20"
close = "2022-06-24 23:59:59"
absddl = "N/A"
submddl = "2021-11-19"
notidue = "2022-02-25"

[[params.cfp.list]]
enable = 1
name = "POPL"
rank = "A"
site = "https://popl22.sigplan.org/"
open = "2022-01-16"
close = "2022-01-21 23:59:59"
absddl = "N/A"
submddl = "2021-07-08 23:59:59 -12:00"
notidue = "2021-10-01"

[[params.cfp.list]]
enable = 1
name = "SOSP"
rank = "A"
site = "https://sosp2021.mpi-sws.org/cfs.html"
open = "2021-10-25"
close = "2021-10-28 23:59:59"
absddl = "2021-04-30 02:59:59 -07:00"
submddl = "2021-05-07 02:59:59 -07:00"
notidue = "2021-08-09"

[[params.cfp.list]]
enable = 0
name = "HotOS"
rank = "B"
site = "https://www.sigops.org/2018/hotos2019/"
open = "2019-05-12"
close = "2019-05-15 23:59:59"
absddl = "N/A"
submddl = "2019-01-17"
notidue = "2019-03-11"

[[params.cfp.list]]
enable = 1
name = "SIGMOD"
rank = "A"
site = "https://2022.sigmod.org/"
open = "2022-06-12"
close = "2022-06-17 23:59:59"
absddl = "N/A"
submddl = "2021-09-15"
notidue = "2022-03-07"

[[params.cfp.list]]
enable = 1
name = "VLDB"
rank = "A"
site = "http://vldb.org/2022/"
open = "2022-09-05"
close = "2022-09-09 23:59:59"
absddl = "2022-02-20"
submddl = "2022-03-01"
notidue = "2022-04-15"

[[params.cfp.list]]
enable = 0
name = "ICDE-1"
rank = "A"
site = "https://icde2021.gr/"
open = "2021-04-19"
close = "2021-04-23 23:59:59"
absddl = "2020-06-10"
submddl = "2020-06-17"
notidue = "2020-10-02"

[[params.cfp.list]]
enable = 1
name = "ICDE"
rank = "A"
site = "https://icde2022.ieeecomputer.my/"
open = "2022-05-09"
close = "2022-05-12 23:59:59"
absddl = "N/A"
submddl = "2021-11-17 23:59:59 -08:00"
notidue = "2021-11-10"

[[params.cfp.list]]
enable = 0
name = "CIDR"
rank = "A"
site = "http://cidrdb.org/cidr2020/"
open = "2020-01-12"
close = "2020-01-15 23:59:59"
absddl = "N/A"
submddl = "2019-08-23 23:59:59 -07:00"
notidue = "2019-10-14"

[[params.cfp.list]]
enable = 1
name = "EMSOFT"
rank = "B"
site = "http://www.esweek.org"
open = "2021-10-10"
close = "2021-10-15 23:59:59"
absddl = "2021-04-02"
submddl = "2021-04-09"
notidue = "2021-07-05"

[[params.cfp.list]]
enable = 1
name = "CODES+ISSS"
rank = "B"
site = "http://www.esweek.org"
open = "2021-10-10"
close = "2021-10-15 23:59:59"
absddl = "2021-04-02"
submddl = "2021-04-09"
notidue = "2021-07-05"

[[params.cfp.list]]
enable = 1
name = "NVMSA"
rank = ""
site = "https://nvmsa2021.github.io/index"
open = "2021-08-18"
close = "2021-08-20 23:59:59"
absddl = "2021-05-14 23:59:59 -12:00"
submddl = "2021-05-21 23:59:59 -12:00"
notidue = "2021-06-25"

[[params.cfp.list]]
enable = 1
name = "HotStorage"
rank = ""
site = "https://www.hotstorage.org/2021/"
open = "2021-07-27"
close = "2021-07-28 23:59:59"
absddl = "N/A"
submddl = "2021-04-30"
notidue = "2021-06-08"

[[params.cfp.list]]
enable = 1
name = "SysML"
rank = ""
site = "https://mlsys.org/"
open = "2022-04-11"
close = "2022-04-14 23:59:59"
absddl = "N/A"
submddl = "2021-10-08 19:59:59"
notidue = "2022-01-15"

[[params.cfp.list]]
enable = 1
name = "FPGA"
rank = "B"
site = "https://isfpga.org/"
open = "2022-02-27"
close = "2022-03-01 23:59:59"
absddl = "2021-09-06"
submddl = "2021-09-06"
notidue = "2021-10-31"

[[params.cfp.list]]
enable = 1
name = "FPL"
rank = "C"
site = "https://www.fpl2021.org/"
open = "2021-08-30"
close = "2021-09-03 23:59:59"
absddl = "2021-03-15"
submddl = "2021-03-22"
notidue = "2021-05-14"

[[params.cfp.list]]
enable = 1
name = "FPT"
rank = "C"
site = "http://www.icfpt.org/"
open = "2021-12-06"
close = "2021-12-10 23:59:59"
absddl = "2021-07-12"
submddl = "2021-07-19"
notidue = "2021-09-10"

[[params.cfp.list]]
enable = 1
name = "FCCM"
rank = "C"
site = "https://www.fccm.org/"
open = "2022-05-15"
close = "2022-05-18 23:59:59"
absddl = "2022-01-03"
submddl = "2022-01-10"
notidue = "2022-03-21"

[[params.cfp.list]]
enable = 1
name = "APSys"
rank = ""
site = "https://ap-sys.org/"
open = "2021-08-24"
close = "2021-08-25 23:59:59"
absddl = "2021-05-20 23:59:00 -04:00"
submddl = "2021-05-27 23:59:00 -04:00"
notidue = "2021-07-01"
