# Page settings
baseurl = "https://cfp.atom.im"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

disableHugoGeneratorInject = true

[blackfriday]
fractions = false
hrefTargetBlank = true

# Meta
[params]
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu Wan"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected conferences in computer architecture & system fields."
notes = "**Note**: Deadlines are shown in timezone from conference website. Timelines and countdowns are shown in Asia/Hong_Kong timezone. Deadlines for conferences with * have not yet been announced."

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://ccf.atom.im). Report bug at [here](https://github.com/atom-im/cfp/issues)."

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im)."

# Timeline section
[params.timeline]
enable = false

# Highlight section
[params.highlight]
enable = true
title = "Featured CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Inactive CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
[params.past]
enable = true
title = "Past CFPs"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event Status"

# Important dates of conferences
# NOTE 1: enable (0: hide, 1: show, 2: highlight)
# NOTE 2: date format: 2006-01-02 15:04:05 -07:00
#         must two digits for each field

[[params.cfp.list]]
enable = 2
name = "ASPLOS Fall"
rank = "A"
site = "https://www.asplos-conference.org/"
open = "2025-03-30"
close = "2025-04-03 23:59:59 -12:00"
absddl = "2024-10-11 23:59:59 -12:00"
submddl = "2024-10-18 23:59:59 -12:00"
notidue = "2025-02-07"

[[params.cfp.list]]
enable = 1
name = "FAST"
rank = "A"
site = "https://www.usenix.org/conference/fast25/call-for-papers"
open = "2025-02-25"
close = "2025-02-27 23:59:59"
absddl = "N/A"
submddl = "2024-09-17 23:59:59 -07:00"
notidue = "2024-12-06"

[[params.cfp.list]]
enable = 1
name = "HPCA"
rank = "A"
site = "https://www.hpca-conf.org/2025/"
open = "2025-03-01"
close = "2025-03-05 23:59:59 +09:00"
absddl = "2024-07-26 23:59:59 +00:00"
submddl = "2024-08-02 23:59:59 +00:00"
notidue = "2024-11-05"

[[params.cfp.list]]
enable = 1
name = "ISCA"
rank = "A"
site = "https://iscaconf.org/isca2024"
open = "2024-06-29"
close = "2024-07-03 23:59:59"
absddl = "2023-11-14 23:59:00 -12:00"
submddl = "2023-11-21 23:59:00 -12:00"
notidue = "2024-03-19"

[[params.cfp.list]]
enable = 1
name = "MICRO"
rank = "A"
site = "https://www.microarch.org/micro57"
open = "2024-11-02"
close = "2024-11-06 23:59:59"
absddl = "2024-04-11 23:59:59 -07:00"
submddl = "2024-04-18 23:59:59 -07:00"
notidue = "2024-07-19"

[[params.cfp.list]]
enable = 1
name = "SC"
rank = "A"
site = "https://sc24.supercomputing.org"
open = "2024-11-17"
close = "2024-11-22 23:59:59"
absddl = "2024-03-26 23:59:00 -12:00"
submddl = "2024-04-02 23:59:00 -12:00"
notidue = "2024-06-16"

[[params.cfp.list]]
enable = 1
name = "ATC"
rank = "A"
site = "https://www.usenix.org/conference/atc24"
open = "2024-07-10"
close = "2024-07-12 23:59:59"
absddl= "2024-01-09 23:59:59 +00:00"
submddl = "2024-01-16 23:59:59 +00:00"
notidue = "2024-04-30"

[[params.cfp.list]]
enable = 1
name = "PPoPP"
rank = "A"
site = "https://ppopp24.sigplan.org"
open = "2024-03-02"
close = "2024-03-06 23:59:59 +09:00"
absddl = "N/A"
submddl = "2023-08-17"
notidue = "2024-01-06"

[[params.cfp.list]]
enable = 1
name = "SPAA"
rank = "B"
site = "http://spaa.acm.org/"
open = "2024-06-17"
close = "2024-06-21 23:59:59"
absddl = "2024-01-19 23:59:59 -12:00"
submddl = "2024-01-24 23:59:59 -12:00"
notidue = "2024-04-07"

[[params.cfp.list]]
enable = 1
name = "PODC"
rank = "B"
site = "https://www.podc.org/"
open = "2024-06-17"
close = "2024-06-21 23:59:59"
absddl = "2024-02-11 23:59:59 -12:00"
submddl = "2024-02-15 23:59:59 -12:00"
notidue = "2024-04-22"

[[params.cfp.list]]
enable = 1
name = "DAC"
rank = "A"
site = "https://dac.com"
open = "2024-06-23"
close = "2024-06-27 23:59:59"
absddl = "2023-11-13 17:00:00 -08:00"
submddl = "2023-11-20 17:00:00 -08:00"
notidue = "2024-02-26"

[[params.cfp.list]]
enable = 1
name = "DATE"
rank = "B"
site = "https://www.date-conference.com/"
open = "2025-03-31"
close = "2025-04-02 23:59:59"
absddl = "2024-09-15 23:59:59 -12:00"
submddl = "2024-09-22 23:59:59 -12:00"
notidue = "2024-11-21"

[[params.cfp.list]]
enable = 1
name = "EuroSys (Fall)"
rank = "A"
site = "https://www.eurosys.org/news/eurosys-2025"
open = "2025-03-30"
close = "2025-04-03 23:59:59"
absddl = "2024-10-15 23:59:59 -12:00"
submddl = "2024-10-22 23:59:59 -12:00"
notidue = "2025-01-25 23:59:59 -12:00"


[[params.cfp.list]]
enable = 1
name = "HPDC"
rank = "B"
site = "http://www.hpdc.org/2024/"
open = "2024-06-03"
close = "2024-06-07 23:59:59"
absddl = "N/A"
submddl = "2024-01-25 23:59:59 -12:00"
notidue = "2024-03-25"

[[params.cfp.list]]
enable = 1
name = "ICCD"
rank = "B"
site = "http://www.iccd-conf.com"
open = "2024-11-06"
close = "2024-11-08 23:59:59"
absddl = "2024-05-20 23:59:59 -12:00"
submddl = "2024-05-20 23:59:59 -12:00"
notidue = "2024-08-01"

[[params.cfp.list]]
enable = 0
name = "ICCAD*"
rank = "B"
site = "http://www.iccad-conf.com"
open = "2025-05-07"
close = "2025-05-09 23:59:59"
absddl = "N/A"
submddl = "2025-01-31"
notidue = "2025-03-31"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS Summer"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2025"
open = "2025-06-09"
close = "2025-06-13 23:59:59"
absddl = "2024-07-31"
submddl = "2024-08-07"
notidue = "2024-09-24"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS Fall"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2025"
open = "2025-06-09"
close = "2025-06-13 23:59:59"
absddl = "2024-10-02"
submddl = "2024-10-09"
notidue = "2024-12-10"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS Winter"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2025"
open = "2025-06-09"
close = "2025-06-13 23:59:59"
absddl = "2025-01-15"
submddl = "2025-01-22"
notidue = "2025-03-18"

[[params.cfp.list]]
enable = 1
name = "ICPP"
rank = "B"
site = "https://icpp2024.org/index.php"
open = "2024-08-12"
close = "2024-08-15 23:59:59"
absddl = "2024-04-22 23:59:59 -12:00"
submddl = "2024-04-29 23:59:59 -12:00"
notidue = "2024-06-10"

[[params.cfp.list]]
enable = 1
name = "ICS"
rank = "B"
site = "https://ics2024.github.io/"
open = "2024-06-04"
close = "2024-06-07 23:59:59"
absddl = "2024-01-11"
submddl = "2024-01-18"
notidue = "2024-04-02"

[[params.cfp.list]]
enable = 1
name = "IPDPS"
rank = "B"
site = "http://www.ipdps.org/"
open = "2024-05-27"
close = "2024-05-31 23:59:59"
absddl = "2023-09-28 23:59:59 -12:00"
submddl = "2023-10-05 23:59:59 -12:00"
notidue = "2024-01-31"

[[params.cfp.list]]
enable = 1
name = "MSST"
rank = "B"
site = "http://storageconference.us/"
open = "2024-06-03"
close = "2024-06-07 23:59:59"
absddl = "N/A"
submddl = "2024-01-17"
notidue = "2024-03-18"

[[params.cfp.list]]
enable = 1
name = "PACT"
rank = "B"
site = "https://pact2024.github.io/"
open = "2024-10-13"
close = "2024-10-16 23:59:59"
absddl = "2024-03-25"
submddl = "2024-04-01"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "OOPSLA"
rank = "A"
site = "https://2024.splashcon.org/"
open = "2024-10-20"
close = "2024-10-25 23:59:59"
absddl = "N/A"
submddl = "2024-04-05"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "ICSE"
rank = "A"
site = "https://conf.researchr.org/home/icse-2025"
open = "2025-04-27"
close = "2025-05-03 23:59:59"
absddl = "2024-07-26 23:59:59 -12:00"
submddl = "2024-08-02 23:59:59 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "OSDI"
rank = "A"
site = "https://www.usenix.org/conference/osdi24/"
open = "2024-07-10"
close = "2024-07-12 23:59:59 -07:00"
absddl = "2023-11-30 22:59:00 +00:00"
submddl = "2023-12-07 22:59:00 +00:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "PLDI"
rank = "A"
site = "http://pldi24.sigplan.org"
open = "2024-06-24"
close = "2024-06-28 23:59:59"
absddl = "N/A"
submddl = "2023-11-16"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "POPL"
rank = "A"
site = "https://popl25.sigplan.org/"
open = "2025-01-19"
close = "2025-01-25 23:59:59"
absddl = "N/A"
submddl = "2024-07-11 23:59:59 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "SOSP"
rank = "A"
site = "https://sigops.org/s/conferences/sosp/2024/"
open = "2024-11-04"
close = "2024-11-06 23:59:59"
absddl = "2024-04-12 02:59:59 -07:00"
submddl = "2024-04-19 02:59:59 -07:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "SIGMOD R3"
rank = "A"
site = "https://2025.sigmod.org/"
open = "2025-06-22"
close = "2025-06-27 23:59:59"
absddl = "2024-07-10"
submddl = "2024-07-17"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "SIGMOD R4"
rank = "A"
site = "https://2025.sigmod.org/"
open = "2025-06-22"
close = "2025-06-27 23:59:59"
absddl = "2024-10-10"
submddl = "2024-10-17"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "VLDB"
rank = "A"
site = "http://vldb.org/2025/"
open = "2025-09-01"
close = "2025-09-05 23:59:59"
absddl = "N/A"
submddl = "2024-07-01"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "ICDE R1"
rank = "A"
site = "https://icde2025.github.io/"
open = "2025-05-19"
close = "2025-05-23 23:59:59"
absddl = "N/A"
submddl = "2024-08-02 23:59:59 -08:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "ICDE R2"
rank = "A"
site = "https://icde2025.github.io/"
open = "2025-05-19"
close = "2025-05-23 23:59:59"
absddl = "N/A"
submddl = "2024-11-28 23:59:59 -08:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 0
name = "CIDR"
rank = "A"
site = "https://www.cidrdb.org/cidr2025/"
open = "2025-01-19"
close = "2025-01-22 23:59:59"
absddl = "N/A"
submddl = "2019-08-02 23:59:59 -07:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 0
name = "ESWEEK"
rank = "B"
site = "http://www.esweek.org"
open = "2024-09-29"
close = "2024-10-04 23:59:59"
absddl = "2022-03-24 23:59:59 -12:00"
submddl = "2022-03-31 23:59:59 -12:00"
notidue = "TBA"


[[params.cfp.list]]
enable = 1
name = "EMSOFT"
rank = "B"
site = "http://www.esweek.org"
open = "2024-09-29"
close = "2024-10-04 23:59:59"
absddl = "2022-03-24 23:59:59 -12:00"
submddl = "2022-03-31 23:59:59 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "CODES+ISSS"
rank = "B"
site = "http://www.esweek.org"
open = "2024-09-29"
close = "2024-10-04 23:59:59"
absddl = "2022-03-24 23:59:59 -12:00"
submddl = "2022-03-31 23:59:59 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "NVMSA"
rank = ""
site = "https://nvmsa2024.github.io/"
open = "2024-08-21"
close = "2024-08-23 23:59:59"
absddl = "2024-04-26"
submddl = "2024-04-28 23:59:59 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "HotStorage"
rank = ""
site = "https://www.hotstorage.org/2024/"
open = "2024-07-08"
close = "2024-07-09 23:59:59"
absddl = "N/A"
submddl = "2024-04-05"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "SysML"
rank = ""
site = "https://mlsys.org/"
open = "2024-05-13"
close = "2024-05-16 23:59:59"
absddl = "N/A"
submddl = "2023-10-27 19:59:59"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "FPGA"
rank = "B"
site = "https://isfpga.org/"
open = "2024-03-03"
close = "2024-03-05 23:59:59"
absddl = "2023-10-06"
submddl = "2023-10-13"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "FPL"
rank = "C"
site = "https://www.fpl.org/"
open = "2024-09-02"
close = "2024-09-06 23:59:59"
absddl = "2024-03-22"
submddl = "2024-03-29"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "FPT"
rank = "C"
site = "http://www.icfpt.org/"
open = "2024-12-10"
close = "2024-12-12 23:59:59"
absddl = "2024-07-14"
submddl = "2024-07-21"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "FCCM"
rank = "C"
site = "https://www.fccm.org/"
open = "2024-05-05"
close = "2024-05-08 23:59:59"
absddl = "2024-01-09"
submddl = "2024-01-15"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "APSys"
rank = ""
site = "https://ap-sys.org/"
open = "2024-09-04"
close = "2024-09-05 23:59:59"
absddl = "2024-04-25 23:59:00 -12:00"
submddl = "2024-05-02 23:59:00 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "RTSS"
rank = "A"
site = "http://2024.rtss.org/"
open = "2024-12-10"
close = "2024-12-13 23:59:59"
absddl = "N/A"
submddl = "2023-05-23 23:59:00 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "RTAS"
rank = "B"
site = "http://2024.rtas.org/"
open = "2024-05-13"
close = "2024-05-16 23:59:59"
absddl = "N/A"
submddl = "2023-10-31 23:59:00 -12:00"
notidue = "TBA"

[[params.cfp.list]]
enable = 1
name = "CGO"
rank = "B"
site = "https://conf.researchr.org/home/cgo-2025"
open = "2025-03-01"
close = "2025-03-05 23:59:59"
absddl = "N/A"
submddl = "2024-09-12 23:59:00 -12:00"
notidue = "TBA"


[[params.cfp.list]]
enable = 1
name = "SAC"
rank = "-"
site = "https://www.sigapp.org/sac/sac2025/"
open = "2025-03-31"
close = "2025-04-04 23:59:59"
absddl = "N/A"
submddl = "2022-09-20 23:59:00 -12:00"
notidue = "TBA"